# Adapted from https://github.com/canonical/observability/blob/v0/.github/workflows/rock-pull-request.yaml
# Notably removed microk8s registry to save on disk space.

name: Pull Requests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    name: Determine modified rocks
    runs-on: ubuntu-24.04
    outputs:
      versions: ${{ steps.changed-versions.outputs.versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Find rockcraft.yaml changes
        id: changed-files
        uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32 # Version 46.0.1
        with:
          files: "**/rockcraft.yaml"
      - name: Extract the versions
        id: changed-versions
        run: |
          versions=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            rock_version="$(dirname $file)"
            versions="${versions# } $rock_version"
          done
          echo "versions=$versions"
          echo "versions=$versions" >> $GITHUB_OUTPUT

  tests:
    name: Tests
    runs-on: ubuntu-24.04
    needs: [changes]
    if: needs.changes.outputs.versions != ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo snap install concierge --classic
          # We need the kubectl (classic) snap because `kgoss` needs access to the /tmp directory
          sudo concierge prepare -p crafts --extra-snaps just
          # FIXME: install via the goss snap when available
          goss_base_url="https://github.com/goss-org/goss/releases/latest/download"
          curl -L ${goss_base_url}/goss-linux-amd64 -o /usr/local/bin/goss
          chmod +rx /usr/local/bin/goss
          sudo apt install containerd
          sudo sh -c 'curl -fsSL https://github.com/containerd/nerdctl/releases/download/v2.2.0/nerdctl-2.2.0-linux-amd64.tar.gz | tar xz -C /usr/bin nerdctl'
      - name: Pack and test the rocks
        run: |
          for version in ${{ needs.changes.outputs.versions }}; do
            just pack "$version"
            just test "$version"
            just clean "$version"
          done
      - name: Open SSH session on failure
        if: ${{ failure() && (runner.debug == '1') }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
        with:
          limit-access-to-actor: true
