name: Update ROCK

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'

jobs:
  build:
    uses: canonical/observability/.github/workflows/rock-update.yaml@main
    with:
      rock-name: grafana-agent
      source-repo: grafana/agent
      check-go: true
